-- Ejecutar en SQL Editor de Supabase para cargar las fotos de la galería

insert into gallery (title, image_url, category) values
-- Momentos
('Compartiendo lecturas', '/images/gallery/momentos/1.jpg', 'Momentos'),
('Taller literario', '/images/gallery/momentos/2.jpg', 'Momentos'),
('Conversando con familiares', '/images/gallery/momentos/3.jpg', 'Momentos'),
('Paseando por la galería', '/images/gallery/momentos/4.jpg', 'Momentos'),
('Amistades', '/images/gallery/momentos/5.jpg', 'Momentos'),
('Merendando', '/images/gallery/momentos/6.jpg', 'Momentos'),
('Cocinando', '/images/gallery/momentos/7.jpg', 'Momentos'),
('Merienda al aire libre', '/images/gallery/momentos/8.jpg', 'Momentos'),
('Paseando por el patio', '/images/gallery/momentos/9.jpg', 'Momentos'),
('Disfrutando del aire libre', '/images/gallery/momentos/10.jpg', 'Momentos'),
('Leyendo', '/images/gallery/momentos/11.jpg', 'Momentos'),
('Mateando', '/images/gallery/momentos/12.jpg', 'Momentos'),
('Momento especial', '/images/gallery/momentos/13.jpg', 'Momentos'),
('Actividad grupal', '/images/gallery/momentos/14.jpg', 'Momentos'),
('Tarde en el patio', '/images/gallery/momentos/15.jpg', 'Momentos'),
('Compartiendo', '/images/gallery/momentos/16.jpg', 'Momentos'),
('Sonrisas', '/images/gallery/momentos/17.jpg', 'Momentos'),
-- Rincón del Sur
('Habitación doble', '/images/gallery/rincon/1.jpg', 'Rincon'),
('Habitación triple', '/images/gallery/rincon/2.jpg', 'Rincon'),
('Vista a la galería', '/images/gallery/rincon/3.jpg', 'Rincon'),
('Patio', '/images/gallery/rincon/4.jpg', 'Rincon'),
('Patio exterior', '/images/gallery/rincon/5.jpg', 'Rincon'),
('Espacio común', '/images/gallery/rincon/6.jpg', 'Rincon'),
('Cocina', '/images/gallery/rincon/7.jpg', 'Rincon'),
('Baño', '/images/gallery/rincon/8.jpg', 'Rincon'),
('Galería', '/images/gallery/rincon/9.jpg', 'Rincon'),
('Dormitorio', '/images/gallery/rincon/10.jpg', 'Rincon'),
('Sala de estar', '/images/gallery/rincon/11.jpg', 'Rincon'),
('Jardín', '/images/gallery/rincon/12.jpg', 'Rincon'),
('Entrada', '/images/gallery/rincon/13.jpg', 'Rincon'),
('Comedor', '/images/gallery/rincon/14.jpg', 'Rincon'),
-- Le-Sa
('Habitación doble', '/images/gallery/lesa/1.jpg', 'Lesa'),
('Habitación triple', '/images/gallery/lesa/2.jpg', 'Lesa'),
('Comedor', '/images/gallery/lesa/3.jpg', 'Lesa'),
('Patio', '/images/gallery/lesa/4.jpg', 'Lesa'),
('Patio exterior', '/images/gallery/lesa/5.jpg', 'Lesa'),
('Cocina', '/images/gallery/lesa/6.jpg', 'Lesa'),
('Baño', '/images/gallery/lesa/7.jpg', 'Lesa'),
('Baño completo', '/images/gallery/lesa/8.jpg', 'Lesa'),
('Galería', '/images/gallery/lesa/9.jpg', 'Lesa'),
('Balcón', '/images/gallery/lesa/10.jpg', 'Lesa'),
('Sala de estar', '/images/gallery/lesa/11.jpg', 'Lesa'),
('Dormitorio', '/images/gallery/lesa/12.jpg', 'Lesa'),
('Espacio común', '/images/gallery/lesa/13.jpg', 'Lesa'),
('Terraza', '/images/gallery/lesa/14.jpg', 'Lesa'),
('Vista interior', '/images/gallery/lesa/15.jpg', 'Lesa'),
('Entrada', '/images/gallery/lesa/16.jpg', 'Lesa');
